name: arknights-vns

services:
  web:
    build: .
    restart: unless-stopped
    depends_on:
      pgbouncer:
        condition: service_healthy
      prisma-studio:
        condition: service_started
    volumes:
      - ./public:/app/public:ro
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT:-3000}:${PORT:-3000}

  postgres:
    image: ghcr.io/arknights-vns/postgres-17:latest
    command: [ "postgres" ]
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data:z
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: edoburu/pgbouncer:v1.24.1-p1
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    depends_on:
      postgres:
        condition: service_started
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: postgres
      # https://stackoverflow.com/a/77794602
      # DB_NAME: ${POSTGRES_DB}
      AUTH_TYPE: scram-sha-256
      POOL_MODE: transaction
      ADMIN_USERS: ${POSTGRES_AUTHORIZED_USERS}
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-h', 'localhost' ]
  prisma-studio:
    image: node:22-trixie
    ports:
      - "51212:51212"
    depends_on:
      postgres:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
    environment:
      DATABASE_DIRECT_URL: ${DATABASE_DIRECT_URL}
    command: [ "sh", "-c", "npx --yes prisma studio --url=\"$DATABASE_DIRECT_URL\" --browser none" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://prisma-studio:51212" ]
      interval: 5s
      timeout: 10s
      retries: 10
