name: arknights-vns

services:
  web:
    container_name: web
    build: .
    hostname: akvns
    restart: unless-stopped
    depends_on:
      pgbouncer:
        condition: service_healthy
      s3:
        condition: service_healthy
      unleash:
        condition: service_healthy
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT:-3000}:${PORT:-3000}

  postgres:
    container_name: postgres
    image: ghcr.io/arknights-vns/postgres-17:latest
    command: [ "postgres" ]
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data:z
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgbouncer:
    container_name: pgbouncer
    image: edoburu/pgbouncer:v1.24.1-p1
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    depends_on:
      postgres:
        condition: service_started
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: postgres
      # https://stackoverflow.com/a/77794602
      # DB_NAME: ${POSTGRES_DB}
      AUTH_TYPE: scram-sha-256
      POOL_MODE: transaction
      ADMIN_USERS: ${POSTGRES_AUTHORIZED_USERS}
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-h', 'localhost' ]

  s3:
    hostname: s3
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${AWS_S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_S3_SECRET_ACCESS_KEY}
      MINIO_REGION: ${AWS_S3_REGION}
    command: server --console-address ":9001" /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://s3:9000/minio/health/live" ]
      interval: 2s
      timeout: 10s
      retries: 5
    volumes:
      - ./s3:/data:z

  unleash:
    container_name: unleash
    image: unleashorg/unleash-server:7
    ports:
      - "4242:4242"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_SSL: "false"
      LOG_LEVEL: "warn"
      INIT_FRONTEND_API_TOKENS: ${INIT_FRONTEND_API_TOKENS}
      INIT_BACKEND_API_TOKENS: ${INIT_BACKEND_API_TOKENS}
      UNLEASH_DEFAULT_ADMIN_USERNAME: ${UNLEASH_DEFAULT_ADMIN_USERNAME}
      UNLEASH_DEFAULT_ADMIN_PASSWORD: ${UNLEASH_DEFAULT_ADMIN_PASSWORD}
    depends_on:
      pgbouncer:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s
