name: arknights-vns

services:
  web:
    build: .
    restart: unless-stopped
    depends_on:
      pgbouncer:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./public:/app/public:ro
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT:-3000}:${PORT:-3000}

  postgres:
    image: ghcr.io/arknights-vns/postgres-17:latest
    command: [ "postgres" ]
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data:z
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: edoburu/pgbouncer:v1.24.1-p1
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    depends_on:
      postgres:
        condition: service_started
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: postgres
      # https://stackoverflow.com/a/77794602
      # DB_NAME: ${POSTGRES_DB}
      AUTH_TYPE: scram-sha-256
      POOL_MODE: transaction
      ADMIN_USERS: ${POSTGRES_AUTHORIZED_USERS}
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-h', 'localhost' ]

  drizzle-gateway:
    image: ghcr.io/drizzle-team/gateway:1.2.0
    ports:
      - "4983:4983"
    volumes:
      - ./volumes/drizzle-gateway:/app:z

  redis:
    image: redis:8.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning /usr/local/etc/redis/redis.conf
    volumes:
      - ./volumes/redis-data:/data:z
      - ./volumes/redis-conf:/usr/local/etc/redis:z
