name: arknights-vns

include:
  - docker/s3/docker-compose.yml

services:
  web:
    container_name: web
    build: .
    hostname: akvns
    restart: unless-stopped
    depends_on:
      pgbouncer:
        condition: service_healthy
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT:-3000}:3000

  postgres:
    container_name: postgres
    image: ghcr.io/arknights-vns/postgres-17:latest
    command: [ "postgres" ]
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data:z
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgbouncer:
    container_name: pgbouncer
    image: edoburu/pgbouncer:v1.24.1-p1
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      # https://stackoverflow.com/a/77794602
      # DB_NAME: ${POSTGRES_DB}
      AUTH_TYPE: scram-sha-256
      POOL_MODE: transaction
      ADMIN_USERS: ${POSTGRES_AUTHORIZED_USERS}
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-h', 'localhost' ]
