name: arknights-vns

include:
  - docker/s3/docker-compose.yml
  - docker/postgres/docker-compose.yml

services:
  web:
    build: .
    hostname: akvns
    restart: unless-stopped
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT:-3000}:3000
